// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/models/device_info_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7405432209100331161),
      name: 'DeviceInfoModel',
      lastPropertyId: const obx_int.IdUid(16, 1628521069859539822),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2937987091944070867),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4617101121302732517),
            name: 'deviceModel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4123934912594529385),
            name: 'osVersion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2042328671769262496),
            name: 'screenResolution',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7756375455551323768),
            name: 'deviceUniqueID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2651978488199996296),
            name: 'networkInformation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3879829215634602046),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7643953303481611759),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3124184973510733336),
            name: 'accuracy',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2696177606151369871),
            name: 'altitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1073001613958236239),
            name: 'heading',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1793393992961518438),
            name: 'speed',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 7833191649478770921),
            name: 'speedAccuracy',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 81972814067184499),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 944481315807892606),
            name: 'nearbyBluetoothDevices',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1628521069859539822),
            name: 'batteryStatusId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 7558304616306338887),
            relationTarget: 'BatteryStatus')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 579432278127944658),
      name: 'BatteryStatus',
      lastPropertyId: const obx_int.IdUid(5, 6208621102409630817),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3209298041598458238),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5284210674761437261),
            name: 'level',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3086738372400523933),
            name: 'charging',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8895713014642087315),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6208621102409630817),
            name: 'deviceInfoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 3694763940197744858),
            relationTarget: 'DeviceInfoModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 579432278127944658),
      lastIndexId: const obx_int.IdUid(2, 7558304616306338887),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DeviceInfoModel: obx_int.EntityDefinition<DeviceInfoModel>(
        model: _entities[0],
        toOneRelations: (DeviceInfoModel object) => [object.batteryStatus],
        toManyRelations: (DeviceInfoModel object) => {},
        getId: (DeviceInfoModel object) => object.id,
        setId: (DeviceInfoModel object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceInfoModel object, fb.Builder fbb) {
          final deviceModelOffset = fbb.writeString(object.deviceModel);
          final osVersionOffset = fbb.writeString(object.osVersion);
          final screenResolutionOffset =
              fbb.writeString(object.screenResolution);
          final deviceUniqueIDOffset = fbb.writeString(object.deviceUniqueID);
          final networkInformationOffset =
              fbb.writeString(object.networkInformation);
          final nearbyBluetoothDevicesOffset = fbb.writeList(object
              .nearbyBluetoothDevices
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(17);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, deviceModelOffset);
          fbb.addOffset(2, osVersionOffset);
          fbb.addOffset(3, screenResolutionOffset);
          fbb.addOffset(4, deviceUniqueIDOffset);
          fbb.addOffset(5, networkInformationOffset);
          fbb.addFloat64(6, object.latitude);
          fbb.addFloat64(7, object.longitude);
          fbb.addFloat64(8, object.accuracy);
          fbb.addFloat64(9, object.altitude);
          fbb.addFloat64(10, object.heading);
          fbb.addFloat64(11, object.speed);
          fbb.addFloat64(12, object.speedAccuracy);
          fbb.addInt64(13, object.timestamp.millisecondsSinceEpoch);
          fbb.addOffset(14, nearbyBluetoothDevicesOffset);
          fbb.addInt64(15, object.batteryStatus.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final deviceModelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final osVersionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final screenResolutionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final deviceUniqueIDParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final networkInformationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final latitudeParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final longitudeParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final accuracyParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final altitudeParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final headingParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final speedParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final speedAccuracyParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0));
          final nearbyBluetoothDevicesParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 32, []);
          final object = DeviceInfoModel(
              deviceModel: deviceModelParam,
              osVersion: osVersionParam,
              screenResolution: screenResolutionParam,
              deviceUniqueID: deviceUniqueIDParam,
              networkInformation: networkInformationParam,
              latitude: latitudeParam,
              longitude: longitudeParam,
              accuracy: accuracyParam,
              altitude: altitudeParam,
              heading: headingParam,
              speed: speedParam,
              speedAccuracy: speedAccuracyParam,
              timestamp: timestampParam,
              nearbyBluetoothDevices: nearbyBluetoothDevicesParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.batteryStatus.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0);
          object.batteryStatus.attach(store);
          return object;
        }),
    BatteryStatus: obx_int.EntityDefinition<BatteryStatus>(
        model: _entities[1],
        toOneRelations: (BatteryStatus object) => [object.deviceInfo],
        toManyRelations: (BatteryStatus object) => {},
        getId: (BatteryStatus object) => object.id,
        setId: (BatteryStatus object, int id) {
          object.id = id;
        },
        objectToFB: (BatteryStatus object, fb.Builder fbb) {
          final levelOffset = fbb.writeString(object.level);
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, levelOffset);
          fbb.addBool(2, object.charging);
          fbb.addOffset(3, statusOffset);
          fbb.addInt64(4, object.deviceInfo.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final levelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final chargingParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = BatteryStatus(
              level: levelParam, charging: chargingParam, status: statusParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.deviceInfo.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.deviceInfo.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DeviceInfoModel] entity fields to define ObjectBox queries.
class DeviceInfoModel_ {
  /// See [DeviceInfoModel.id].
  static final id =
      obx.QueryIntegerProperty<DeviceInfoModel>(_entities[0].properties[0]);

  /// See [DeviceInfoModel.deviceModel].
  static final deviceModel =
      obx.QueryStringProperty<DeviceInfoModel>(_entities[0].properties[1]);

  /// See [DeviceInfoModel.osVersion].
  static final osVersion =
      obx.QueryStringProperty<DeviceInfoModel>(_entities[0].properties[2]);

  /// See [DeviceInfoModel.screenResolution].
  static final screenResolution =
      obx.QueryStringProperty<DeviceInfoModel>(_entities[0].properties[3]);

  /// See [DeviceInfoModel.deviceUniqueID].
  static final deviceUniqueID =
      obx.QueryStringProperty<DeviceInfoModel>(_entities[0].properties[4]);

  /// See [DeviceInfoModel.networkInformation].
  static final networkInformation =
      obx.QueryStringProperty<DeviceInfoModel>(_entities[0].properties[5]);

  /// See [DeviceInfoModel.latitude].
  static final latitude =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[6]);

  /// See [DeviceInfoModel.longitude].
  static final longitude =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[7]);

  /// See [DeviceInfoModel.accuracy].
  static final accuracy =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[8]);

  /// See [DeviceInfoModel.altitude].
  static final altitude =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[9]);

  /// See [DeviceInfoModel.heading].
  static final heading =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[10]);

  /// See [DeviceInfoModel.speed].
  static final speed =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[11]);

  /// See [DeviceInfoModel.speedAccuracy].
  static final speedAccuracy =
      obx.QueryDoubleProperty<DeviceInfoModel>(_entities[0].properties[12]);

  /// See [DeviceInfoModel.timestamp].
  static final timestamp =
      obx.QueryDateProperty<DeviceInfoModel>(_entities[0].properties[13]);

  /// See [DeviceInfoModel.nearbyBluetoothDevices].
  static final nearbyBluetoothDevices =
      obx.QueryStringVectorProperty<DeviceInfoModel>(
          _entities[0].properties[14]);

  /// See [DeviceInfoModel.batteryStatus].
  static final batteryStatus =
      obx.QueryRelationToOne<DeviceInfoModel, BatteryStatus>(
          _entities[0].properties[15]);
}

/// [BatteryStatus] entity fields to define ObjectBox queries.
class BatteryStatus_ {
  /// See [BatteryStatus.id].
  static final id =
      obx.QueryIntegerProperty<BatteryStatus>(_entities[1].properties[0]);

  /// See [BatteryStatus.level].
  static final level =
      obx.QueryStringProperty<BatteryStatus>(_entities[1].properties[1]);

  /// See [BatteryStatus.charging].
  static final charging =
      obx.QueryBooleanProperty<BatteryStatus>(_entities[1].properties[2]);

  /// See [BatteryStatus.status].
  static final status =
      obx.QueryStringProperty<BatteryStatus>(_entities[1].properties[3]);

  /// See [BatteryStatus.deviceInfo].
  static final deviceInfo =
      obx.QueryRelationToOne<BatteryStatus, DeviceInfoModel>(
          _entities[1].properties[4]);
}
